on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run the Action
        id: hello
        uses: ./
        with:
          myInput: 'Igor Holovka'
      - name: output
        run: |
          echo ${{ steps.hello.outputs.memory }}
          echo "total memory sucesfully output"